/*
==============================================================================
Part-to-Whole Analysis
==============================================================================

Purpose:
    Analyze how individual business segments contribute to the overall
    business performance. This analysis helps identify the relative
    importance of each category and supports strategic decision-making.

Objectives:
    1. Calculate total sales for each product category.
    2. Compute overall business sales.
    3. Determine each category's percentage contribution to total revenue.
    4. Rank categories based on their contribution.

Tables Used:
    - gold.fact_sales
    - gold.dim_products

SQL Concepts Used:
    - Common Table Expressions (CTEs)
    - Aggregate Functions
        • SUM()
    - Window Functions
        • SUM() OVER()
    - ROUND()
    - CAST()

==============================================================================
*/

-------------------------------------------------------------------------------
-- 1. Category Sales
--
-- Aggregates total revenue generated by each product category.
-------------------------------------------------------------------------------

WITH category_sales AS
(
    SELECT
        dp.category,
        SUM(fs.sales_amount) AS total_sales
    FROM gold.fact_sales AS fs
    INNER JOIN gold.dim_products AS dp
        ON fs.product_key = dp.product_key
    GROUP BY
        dp.category
)

-------------------------------------------------------------------------------
-- 2. Category Contribution Analysis
--
-- Calculates:
--   • Total sales by category
--   • Overall business sales
--   • Percentage contribution of each category to total revenue
-------------------------------------------------------------------------------

SELECT
    category,

    total_sales,

    SUM(total_sales) OVER () AS overall_sales,
    
    CONCAT(
        ROUND(
            CAST(total_sales AS FLOAT)
            /
            SUM(total_sales) OVER ()
            * 100,
            2),
         '%'
    ) AS percentage_of_total_sales

FROM category_sales

ORDER BY
    total_sales DESC;

-------------------------------------------------------------------------------
-- End of Part-to-Whole Analysis
-------------------------------------------------------------------------------